RANK_W = {
1:'Stefanie Blendermann',
2:'Lara Jehle',
3:'Melanie Hammerschmidt',
4:'Anna Bandera',
5:'Michaela Krane',
6:'Karin Olsson',
7:'Jasmin Bothmann',
8:'Sandra Kungsman',
9:'Carolin Svensson',
10:'Mia Vuorihovi',
11:'Julia Sjöberg',
12:'Martina Maderová',
13:'Nadine Jürgens',
14:'Lucie Indráková',
15:'Michaela Irxenmayer',
16:'Mirva Juhola',
}

RANK_M = {
1:'Yannick Müller',
2:'Eirik Seljelid',
3:'Ulf Kristiansson',
4:'Carl-Johan Ryner',
5:'Fredrik Persson',
6:'Lukas Neumann',
7:'Ondřej Škaloud',
8:'Severin Blümer',
9:'Andreas Schneider',
10:'Thomas Lottermoser',
11:'Daniel Moser',
12:'Sebastian Heine',
13:'Lars Anderegg',
14:'Kenny Marc Schmeckenbecher',
15:'Paolo Porta',
16:'Zdenek Majkus',
17:'Alexander Princis',
18:'Hannes Laimer',
19:'Mario Dangl',
20:'Duccio Cheli',
21:'Reto Sommer',
22:'Sebastian Piekorz',
23:'Rikard Lindqvist',
24:'Beat Wartenweiler',
25:'Maxime Bugnion',
26:'Marián Straško',
27:'Kai Lödding',
28:'Oleg Klassen',
29:'Filip Cervinka',
30:'Marco Broggi',
31:'Simon Junker',
32:'Mathias Jagschitz',
}